### ISSUE TITLE
working-directory input not working

### ISSUE THREAD

**Issue by CraigWilson-ZOE** [yu-iskw/action-sqlfluff#11]
When I try to run the action, it is always running in `/github/home` and this is inaccessible.

I have attempted to move my `profiles.yml` file to `/github/home/.dbt` but I do not have permissions to create that directory and it does not exist.

I have attempted to change the working directory as an input but each time it runs the action runs in the `/github/home` directory looking for `.dbt/` which again does not exist and cannot be created due to permissions.

I also checked the `${{ github.workspace }}` which is supposed to be the default, but for my step `setup dbt` this is different to where the action is running. For my custom step it is `/home/runner/work/dbt-bq-elt/dbt-bq-elt` and where the action tries to run is `/github/home`.

Here is my configuration for the action. Note I am attempting to create a `profiles.yml` file in the `setup dbt` section in order for SQLFluff to correctly connect to our BigQuery warehouse:

```
name: sqlfluff with reviewdog
on:
  pull_request:
jobs:
  test-check:
    name: runner / sqlfluff (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'setup dbt'
        shell: bash
        run: |
          echo "${{ secrets.gcloud_service_key }}" > "${{ github.workspace }}/dbt-service-account.json"
          sed s/template-project-id/${{ secrets.GOOGLE_PROJECT_ID }}/g profiles.github.yaml > profiles.github1.yaml
          sed -i s,template-json-directory,${{ github.workspace }},g profiles.github1.yaml > profiles.github2.yaml
          mkdir -p "~/.dbt"
          mkdir "${{ github.workspace }}/.dbt"
          mv profiles.github2.yaml "~/.dbt/profiles.yml"
      - uses: yu-iskw/action-sqlfluff@v2
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "0.9.1"
          working-directory: /home/runner
          config: "${{ github.workspace }}/.sqlfluff"
          paths: '${{ github.workspace }}/models'
          fail_on_error: true
      - name: 'Show outputs (Optional)'
        shell: bash
        run: |
          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'
```
