### ISSUE TITLE
What is the best way to use inside docker-compose project?

### ISSUE THREAD

**Issue by simpl1g** [yu-iskw/action-sqlfluff#25]
I have dbt inside docker compose with all dependencies.

Currently, I'm running check that compilation successful in PR's like this

```yml
name: dbt
on: pull_request
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start docker compose
        run: docker compose up -d
      - name: Compile sources
        run: docker compose exec service dbt compile
      - name: Stop compose
        if: always()
        run: |
          docker-compose down
          docker network prune -f
```

I'm trying to add sqlfluff linter, and it requires all database dependencies to be set manually. 
However I can run command inside compose
```shell
docker compose exec service sqlfluff lint --format json --dialect postgres --templater dbt ...
```

Is it possible to utilize this? Or should I build workflow from scratch?

**Comment by simpl1g** [comment]
Works fine with annotations format

```yml
      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v19
        with:
          files: 'models/**/*.sql'
      - name: Lint
        if: steps.changed_files.outputs.any_changed == 'true'
        run: docker compose exec dbt sqlfluff lint --format github-annotation --dialect ansi --templater dbt --nofail ${{ steps.changed_files.outputs.all_changed_files }} > annotations.json
      - name: Annotate
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: "SQLFluff Lint"
          input: "./annotations.json"
```
