### ISSUE TITLE
Fail action when there are violations

### ISSUE THREAD

**Issue by sowusu-ba** [yu-iskw/action-sqlfluff#29]
The action always shows a green check-mark even if there are violations after linting
<img width="1309" alt="Screen Shot 2022-06-08 at 9 12 00 AM" src="https://user-images.githubusercontent.com/99834914/172653026-8e3c204d-e872-42c6-ac33-001f62984950.png">

Is there any of the inputs that need to be changed to make it show a red x when there are any violations after linting?

my yml file has this

```
name: Code QA
on:
  pull_request:
jobs:
  test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "0.13.0"
          sqlfluff_command: "lint" # Or "fix"
          fail_on_error: 'true'
          config: "${{ github.workspace }}/.github/linters/.sqlfluff"
          paths: '${{ github.workspace }}/dbt/models'
      - name: 'Show outputs (Optional)'
        shell: bash
        run: |
          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'
```

I was hoping `fail_on_error` would do the trick but it didn't
