### ISSUE TITLE
Fail action when there are violations

### ISSUE THREAD

**Issue by kaysef** [yu-iskw/action-sqlfluff#30]
The action always shows a green check-mark even if there are violations after linting
<img width="1309" alt="Screen Shot 2022-06-08 at 9 12 00 AM" src="https://user-images.githubusercontent.com/99834914/172653026-8e3c204d-e872-42c6-ac33-001f62984950.png">

Is there any of the inputs that need to be changed to make it show a red x when there are any violations after linting?

my yml file has this

```
name: Code QA
on:
  pull_request:
jobs:
  test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "0.13.0"
          sqlfluff_command: "lint" # Or "fix"
          fail_on_error: 'true'
          config: "${{ github.workspace }}/.github/linters/.sqlfluff"
          paths: '${{ github.workspace }}/dbt/models'
      - name: 'Show outputs (Optional)'
        shell: bash
        run: |
          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'
```

I was hoping `fail_on_error` would do the trick but it didn't

**Comment by yu-iskw** [comment]
We have a dilemma to return a failed status code of reviewdog, because reviewdog doesn't leave suggestion if failed. We are blocked by the issue on reviewdog side to solve the issue.

- https://github.com/reviewdog/reviewdog/issues/949

**Comment by kieronellis** [comment]
Hi, I'm having trouble accessing the `sqlfluff-exit-code` output to be able to raise an error if there is a failure, is it something I've done incorrectly or is there an issue with accessing this output?

```
name: sqlfluff with reviewdog
on:
  pull_request:
jobs:
  test-check:
    name: runner / sqlfluff (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Decode service account credentials
        env:
          # The base64 encoded credentials.
          GOOGLE_APPLICATION_CREDENTIALS_BASE64: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}"
        run: |
          echo "...Decoding GOOGLE_APPLICATION_CREDENTIALS_BASE64..."
          python decode_base64.py || exit 1
          echo "...and validating json output..."
          python -m json.tool gcloud.json > /dev/null || exit 1

      - uses: yu-iskw/action-sqlfluff@v3.3.2
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/.github/sqlfluff/.dbt/
        id: lint_sql
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          reporter: github-pr-review
          sqlfluff_version: "1.1.0"
          sqlfluff_command: "fix" # Or "lint"
          config: "${{ github.workspace }}/setup.cfg"
          paths: '${{ github.workspace }}/models'
          fail_on_error: true
          dialect: bigquery
          extra_requirements_txt: "${{ github.workspace }}/requirements.txt"

      - name: 'Show outputs (Optional)'
        shell: bash
        run: |
          echo '${{ steps.lint_sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.lint_sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'

          echo "${{ steps.lint_sql.outputs.sqlfluff-exit-code }}"
          echo ${{ steps.lint_sql.outputs.sqlfluff-exit-code }}
          if [ "${{ steps.lint_sql.outputs.sqlfluff-exit-code }}" != "sqlfluff 0" ]; then echo "SQLFluff did not exit 0" ;fi
          if [ "${{ steps.lint_sql.outputs.sqlfluff-exit-code }}" != "sqlfluff 0" ]; then exit 1 ;fi
```

Neither `sqlfluff-results`, `sqlfluff-results-rdjson` or `sqlfluff-exit-code` echo's anything. Why are these empty? 

Any help would be appreciated!
