### ISSUE TITLE
Can't get changed files.

### ISSUE THREAD

**Issue by tenajima** [yu-iskw/action-sqlfluff#34]
My repository is like this.
```
.
├── README.md
├── other_directory
│   └── other_files
├── dbt
│   ├──.sqlfluff
│   ├──packages.yml
|   └── models
```
And I want to lint to `dbt/models/`. So my yaml for workflow write like this.
```
name: sqlfluff with reviewdog
on:
  pull_request:
jobs:
  test-check:
    name: runner / sqlfluff (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: auth
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: unipos-dev-diu
          service_account_key: ${{ secrets.gcp_key }}
          export_default_credentials: true
      - uses: yu-iskw/action-sqlfluff@v3.3.1
        id: lint-sql
        env:
          GCLOUD_PROJECT: my-project
        with:
          working-directory: ./dbt
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "0.13.0"
          sqlfluff_command: "lint"
          config: "./.sqlfluff"
          paths: './models'
          extra_requirements_txt: './extra_requirements.txt'
      - name: 'Show outputs (Optional)'
        shell: bash
        run: |
          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'
```
I think setting `woriking-directory` is required, because of running `dbt deps`. But, then [here](https://github.com/yu-iskw/action-sqlfluff/blob/31c5f006bf98f6099a789578a6157ec3f8353aa6/entrypoint.sh#L16) is not working well...
I expect `models/marts/hoge.sql`, but `git diff --name-only --no-color sqlfluff_bot HEAD` returns `dbt/models/marts/hoge.sql`.
There is any solutions ?
