### ISSUE TITLE
reviewdog outputs raw format instead of code suggestion

### ISSUE THREAD

**Issue by yaozhang09** [yu-iskw/action-sqlfluff#56]
When running sqlfluff fix on  changes that end up being more than a few lines of sql, instead of a code suggestion on pr review it gets outputted in raw format.  Wondering why that's the case or if there is something with my workflow implementation?

small change:
<img width="559" alt="Screenshot 2023-01-12 at 3 12 33 PM" src="https://user-images.githubusercontent.com/114429763/212200987-a1e02ba3-96e4-42fd-b846-b98c6b67ef98.png">

change that is over 20 lines long:
<img width="934" alt="Screenshot 2023-01-12 at 3 21 11 PM" src="https://user-images.githubusercontent.com/114429763/212202164-f241495d-a9ef-4ed4-8ab3-66fb39743ecd.png">

.sqlfluff config:
```[sqlfluff]
dialect = bigquery
templater = dbt
rules = core
exclude_rules = L008, L032, L031, L040

[sqlfluff:templater:dbt]
project_dir = .

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:rules]
capitalisation_policy = consistent
extended_capitalisation_policy = consistent

[sqlfluff:rules:L016]
max_line_length = 200
```

workflow:
```
steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: yu-iskw/action-sqlfluff@v3.5.0
        id: fix-sql
        env: 
          DBT_PROFILES_DIR: '${{ github.workspace }}/dbt'
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: '${{ github.workspace }}/dbt'
          level: 'warning'
          reporter: github-pr-review
          filter_mode: 'added'
          reviewdog_version: '0.14.1'
          sqlfluff_version: '1.4.5'
          sqlfluff_command: 'fix'
          paths:  "${{ github.workspace }}/dbt/models"
          config: "${{ github.workspace }}/dbt/.sqlfluff"
          extra_requirements_txt: "${{ github.workspace }}/dbt/sqlfluff_requirements.txt"
      
      - name: 'Show outputs (Optional)'
        shell: bash
        run: |
          echo '${{ steps.fix-sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.fix-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'
```
