### ISSUE TITLE
 fatal: --unshallow on a complete repository does not make sense

### ISSUE THREAD

**Issue by oynek** [yu-iskw/action-sqlfluff#74]
When using this GitHub Action, I encounter the following error message:
```
🐶 Get changed files
  fatal: --unshallow on a complete repository does not make sense
```

I suspect the error [here](https://github.com/yu-iskw/action-sqlfluff/blob/a28280f53bbb888a7a1c8d560c01b32b97269198/entrypoint.sh#LL17C40-L17C40), but do not understand why this occurs.

My workflow file:
```
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Lint added and modified .sql files
        uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "1.4.5"
          sqlfluff_command: "lint"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: "${{ github.workspace }}/models"
          extra_requirements_txt: "${{ github.workspace }}/.github/config/requirements.txt"
```
