### ISSUE TITLE
action-sqlfluff GH action outputs raw format instead of inline code suggestion

### ISSUE THREAD

**Issue by armaandhull** [yu-iskw/action-sqlfluff#79]
@yu-iskw The issue reported in #56 is still present when the diff produced by `sqlfluff fix` is bigger than a few lines (including a screenshot below). Do we have a fix/workaround for it?

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/2514782/231847675-dda3be9e-9425-4dff-ba2d-7d9db730a1ca.png">

The relevant config from the workflow yaml file
```
    steps:
      - uses: actions/checkout@v2
      - uses: yu-iskw/action-sqlfluff@v3
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "1.4.5"
          sqlfluff_command: "fix"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: "${{ github.workspace }}/models"
          extra_requirements_txt: "${{ github.workspace }}/requirements.txt"
      - name: "Show outputs (Optional)"
        shell: bash
        run: |
          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'
```
